# deploy.yml
---
- name: Deploy Application Locally
  hosts: all

  tasks:
    - name: Copy Docker Compose file from host machine to remote host
      ansible.builtin.copy:
        src: ./docker-compose.yml
        dest: ./
        remote_src: yes
      tags:
        - copy_files

    - name: Pull the docker images specified in docker-compose
      command: docker-compose pull

    - name: Run the pulled docker images in detached mode
      command: docker-compose up -d

    - name: Prune the dangling docker images
      command: docker image prune --force

