version: '3.3'

services:
  mongodb:
    container_name: mongo_service
    restart: always
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: adminpassword
    ports:
      - "27017:27017"  # Expose MongoDB port
    volumes:
      - mongo_data:/data/db
    networks:
      - exptrack

  mongodb-tools:
    container_name: mongo_tools
    image: ubuntu:20.04
    command: bash -c "apt-get update && apt-get install -y mongodb-clients && tail -f /dev/null"
    networks:
      - exptrack
    depends_on:
      - mongodb
      
  exptrack-backend:
    build:
      dockerfile: Dockerfile 
      context: ./backend/
    container_name: exptrack-backend
    restart: always
    image: gatsy1227/back1:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: adminpassword
    stdin_open: true
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/backend
      - /backend/node_modules
    networks:
      - exptrack

  exptrack-frontend:
    build:
      dockerfile: Dockerfile
      context: ./frontend/
    container_name: exptrack-frontend
    restart: always
    image: gatsy1227/front1:latest
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/frontend
      - ./frontend/node_modules
    networks:
      - exptrack
    depends_on:
      - exptrack-backend

volumes:
  mongo_data:
    driver: local

networks:
  exptrack:
    driver: bridge
