version: '3.3'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: adminpassword
      MONGO_INITDB_DATABASE: mydatabase
    ports:
      - "27017:27017"  # Expose MongoDB port
    volumes:
      - mongo_data:/data/db
    networks:
      - exptrack
  exptrack-frontend:
    image: gatsy1227/front1:latest
    container_name: exptrack-frontend
    stdin_open: true
    ports:
      - "3000:3000"
    networks:
      exptrack:
        ipv4_address: 172.18.1.6

  exptrack-backend:
    image: gatsy1227/back1:latest
    container_name: exptrack-backend
    ports:
      - "5000:5000"
    networks:
      exptrack:
        ipv4_address: 172.18.1.7
volumes:
  mongo_data:
    driver: local

networks:
  exptrack:
    ipam:
      driver: default
      config:
        - subnet: 172.18.1.0/24
